### PR TITLE
Update to preserve media queries

### PR DESCRIPTION
**Pull request by gavmck**
We needed responsive emails using Zurb's inky and I noticed this library doesn't preserve them.
Was going to move over to juice, but ended up just adding the preserve email option in inlineCSS.

### CODE REVIEW

**Comment by XavRsl** [comment]
Guess I'll have to make a new version. Will do that tomorrow

**Comment by gavmck** [comment]
Awesome, thanks for the merge! Super useful module you have here.

**Comment by XavRsl** [comment]
Really ? Thanks. In fact, I'm not sure I'll be using it again so much. 

Thanks for your work.

Xavier

**Comment by gavmck** [comment]
Why not? Have you got a different solution now?

**Comment by XavRsl** [comment]
I'm looking at what Taylor Otwell just annonced yesterday. the notification
sysytem from Laravel 5.3 is already very elegant, but what will be
available in 5.4 is just a perfect solution to me.

Xavier

Le mar. 13 déc. 2016 à 12:34, Gavyn McKenzie <notifications@github.com> a
écrit :

**Comment by gavmck** [comment]
Whoa, just had a look! That's epic. Thanks for the heads up.

**Comment by XavRsl** [comment]
I know !!!!

Le mar. 13 déc. 2016 à 15:30, Gavyn McKenzie <notifications@github.com> a
écrit :

> Whoa, just had a look! That's epic. Thanks for the heads up.
>

**Pull request merged**
